# Generated by Django 5.0.6 on 2024-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True, verbose_name='Event ID')),
                ('account_id', models.UUIDField(unique=True, verbose_name='Account ID')),
                ('created_at', models.DateTimeField(verbose_name='Creation Datetime')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('data', models.JSONField(verbose_name='Event Data')),
            ],
            options={
                'verbose_name': 'Account Event',
                'verbose_name_plural': 'Account Events',
            },
        ),
        migrations.CreateModel(
            name='AccountProjectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('type', models.CharField(max_length=100, verbose_name='Account Type')),
                ('balance', models.IntegerField(verbose_name='Account Balance')),
            ],
            options={
                'verbose_name': 'Account Projection',
                'verbose_name_plural': 'Account Projections',
            },
        ),
    ]
