# Generated by Django 5.0.6 on 2024-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprojectionmodel',
            name='category',
            field=models.CharField(default='budget', max_length=100, verbose_name='Account Category'),
            preserve_default=False,
        ),
    ]
