# Generated by Django 4.1.2 on 2024-05-19 18:37

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('accounts', 'AccountModel')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]

