# Generated by Django 5.0.6 on 2024-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprojectionmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionProjectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('date', models.DateField(verbose_name='Date')),
                ('payee_id', models.CharField(max_length=100, verbose_name='Payee ID')),
                ('category_id', models.CharField(max_length=100, verbose_name='Category ID')),
                ('memo', models.TextField(max_length=100, verbose_name='Memo')),
                ('outflow', models.IntegerField(verbose_name='Outflow')),
                ('inflow', models.IntegerField(verbose_name='Inflow')),
                ('cleared', models.BooleanField(verbose_name='Cleared')),
            ],
            options={
                'verbose_name': 'Transaction Projection',
                'verbose_name_plural': 'Transaction Projections',
            },
        ),
    ]
