# Generated by Django 4.1.2 on 2024-05-19 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
