# Generated by Django 5.0.6 on 2024-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactionprojectionmodel_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounteventmodel',
            name='account_id',
            field=models.UUIDField(verbose_name='Account ID'),
        ),
    ]
