# Generated by Django 5.0.6 on 2024-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounteventmodel_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionprojectionmodel',
            name='reconciled',
            field=models.BooleanField(default=True, verbose_name='Reconciled'),
            preserve_default=False,
        ),
    ]
